In [1]:
import json
import pandas as pd   
import yaml
import numpy as np
import sqlite3
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
data = []
c = 0

with open('meta_Clothing_Shoes_and_Jewelry.jsonl') as f:
    for line in f:
        data.append(json.loads(line))
        c+=1        
        if c == 17000:
            break

In [3]:
data_df = pd.DataFrame(data)

In [4]:
data_df['gender'] = data_df['categories'].str[1]
data_df['type'] = data_df['categories'].str[2]
data_df['misc'] = data_df['categories'].str[3]

In [5]:
data_df = data_df.drop(['features', 'images', 'description', 'videos', 'categories', 'parent_asin', 'details', 'bought_together', 'subtitle', 'author'], axis=1)

data_df.dropna(subset=['price'], inplace=True)

In [8]:
data_df.reset_index(inplace = True, drop=False)
data_df.rename(columns={'index': "id"})

,level_0,id,main_category,title,average_rating,rating_number,price,store,gender,type,misc
0,0,0,AMAZON FASHION,BALEAF Women's Long Sleeve Zip Beach Coverup U...,4.2,422,31.99,BALEAF,Women,Clothing,Swimsuits & Cover Ups
1,1,2,AMAZON FASHION,"SAS Women's, Relaxed Sandal",4.7,618,188.95,SAS,Women,Shoes,Sandals
2,2,3,AMAZON FASHION,SheIn Women's Basic Stretch Plaid Mini Bodycon...,3.8,999,12.99,SheIn,Novelty & More,Clothing,Novelty
3,3,7,AMAZON FASHION,Costume Gloves Kids Girls Boys Princess Dress ...,4.4,30,9.59,unbrands,Novelty & More,Clothing,Novelty
4,4,8,AMAZON FASHION,Chowsir Women Fashion V-Neck Formal Lace Eveni...,4.3,127,22.19,Chowsir,Women,Clothing,Dresses
...,...,...,...,...,...,...,...,...,...,...,...
9227,9227,16995,AMAZON FASHION,PRETTYGARDEN Women's Zip Up Y2K Hoodies Casual...,4.4,268,42.99,PRETTYGARDEN,Women,Clothing,"Coats, Jackets & Vests"
9228,9228,16996,AMAZON FASHION,Add Your Own Text and Design Custom Personaliz...,4.4,2821,45.90,City Shirts,Novelty & More,Clothing,Novelty
9229,9229,16997,AMAZON FASHION,Red Rock Outdoor Gear - Shemagh Head Wrap,4.5,550,10.59,Red Rock Outdoor Gear,Men,Clothing,NaN
9230,9230,16998,AMAZON FASHION,Metallic Wrist Length Gloves,3.4,12,13.05,Greatlookz,Women,Accessories,Special Occasion Accessories
9231,9231,16999,AMAZON FASHION,Venshine Mens Walking Shoes Leather Lightweigh...,4.3,3922,59.99,Venshine,Men,Shoes,Loafers & Slip-Ons

In [14]:
data_df['type'].unique()

array(['Clothing', 'Shoes', 'Uniforms, Work & Safety', 'Accessories',
       'Kids & Baby', 'Backpacks', 'Women', 'Jewelry Accessories',
       'Jewelry', nan, 'Running', 'Baby Girls', 'Men',
       'Travel Accessories', 'Handbags & Wallets', 'Cheerleading',
       'Baby Boys', 'Watches', 'Dance', 'Cycling', 'Soccer & Futsal',
       'Skiing', 'Watch Accessories', 'Basketball',
       'Hiking & Outdoor Recreation', 'Travel Totes',
       'Competitive Swimwear', 'Maternity', 'School Uniforms',
       'Umbrellas', 'Martial Arts', 'Gym Bags', 'Yoga',
       'Shoe Care & Accessories', 'Waist Packs', 'Girls',
       'Equestrian Sports', 'Props', 'Ice Hockey', 'Baseball',
       'Messenger Bags', 'Travel Duffels', "Men's Swimwear", 'Luggage',
       'Golf', 'Boys Shoes', 'Boys', 'Gymnastics', 'Softball',
       'Girls Tops & Tees 1', 'Ice Skating', 'Food Service Uniforms',
       'American Football', 'Snowboarding', 'Jackets and Coats',
       'Womens GenZ Shoes', 'Shoe Care Treatments & Dyes',
       'TEST W GENZ SHOES', "Boys' Swimwear", 'Volleyball',
       "Women's fashion Made in Italy", 'Boys Sneakers (no fs)',
       'Girls Boots, Clogs & Mules', 'Tennis', 'Girls Jackets and Coats',
       'Cricket', 'Boxing', 'Makeup, Facial Hair & Adhesives'],
      dtype=object)

In [149]:
data_full = data_df[["index", "main_category", "title", "average_rating", "rating_number", "price", "store", "gender", "type", "misc"]]

engine = create_engine('sqlite:///instance/amazon.db')
data_full.to_sql('Inventory', con=engine, index=False, if_exists='replace')

9232

In [150]:
data_df

,index,main_category,title,average_rating,rating_number,price,store,gender,type,misc
0,0,AMAZON FASHION,BALEAF Women's Long Sleeve Zip Beach Coverup U...,4.2,422,31.99,BALEAF,Women,Clothing,Swimsuits & Cover Ups
1,2,AMAZON FASHION,"SAS Women's, Relaxed Sandal",4.7,618,188.95,SAS,Women,Shoes,Sandals
2,3,AMAZON FASHION,SheIn Women's Basic Stretch Plaid Mini Bodycon...,3.8,999,12.99,SheIn,Novelty & More,Clothing,Novelty
3,7,AMAZON FASHION,Costume Gloves Kids Girls Boys Princess Dress ...,4.4,30,9.59,unbrands,Novelty & More,Clothing,Novelty
4,8,AMAZON FASHION,Chowsir Women Fashion V-Neck Formal Lace Eveni...,4.3,127,22.19,Chowsir,Women,Clothing,Dresses
...,...,...,...,...,...,...,...,...,...,...
9227,16995,AMAZON FASHION,PRETTYGARDEN Women's Zip Up Y2K Hoodies Casual...,4.4,268,42.99,PRETTYGARDEN,Women,Clothing,"Coats, Jackets & Vests"
9228,16996,AMAZON FASHION,Add Your Own Text and Design Custom Personaliz...,4.4,2821,45.90,City Shirts,Novelty & More,Clothing,Novelty
9229,16997,AMAZON FASHION,Red Rock Outdoor Gear - Shemagh Head Wrap,4.5,550,10.59,Red Rock Outdoor Gear,Men,Clothing,NaN
9230,16998,AMAZON FASHION,Metallic Wrist Length Gloves,3.4,12,13.05,Greatlookz,Women,Accessories,Special Occasion Accessories
9231,16999,AMAZON FASHION,Venshine Mens Walking Shoes Leather Lightweigh...,4.3,3922,59.99,Venshine,Men,Shoes,Loafers & Slip-Ons

In [ ]:
cust_stats_f = data_df[["customer_id", "total_orders", "total_items", "total_spent"]]

engine = create_engine('sqlite:///PEP1_db.db')
orders_f.to_sql('orders', con=engine, index=False, if_exists='replace')

In [5]:
data_df.to_csv("Clothing_Data_small.csv")

In [8]:
with open('meta_Clothing_Shoes_and_Jewelry.jsonl', 'r') as json_file:
    data = json.load(json_file)

    chunk_size = len(data) // 1000

    for i in range(3):
        print(i)
        # with open(f"part{i}.json", 'w') as outfile:
        #     outfile.write(json.dumps(data[i*chunk_size:(i+1)*chunk_size]))

MemoryError: